config_files/pipeline_vod_encrypted_raw_config.yaml, streamer/input_configuration.py, streamer/packager_node.py, streamer/pipeline_configuration.py, tests/tests.js
See #21 - Adds support for using raw key encryption.
Retains backwards compatibility with the existing Widevine encryption by adding an `encryption_mode` directive to the encryption configuration.
Also adds drm_label and skip_encryption to inputs.
=> Shaka Packager Raw Key support

config_files/bitrate_hls_config.yaml
Apple's recommended bitrates over HLS.
not all the values for different video resolutions and audio channel layouts are documented.
some values are made up by me.
=> added recommended bitrates for HLS

streamer/bitrate_configuration.py, streamer/transcoder_node.py
Using same FFmpeg parameters as h264 for the most part but letting the encoder choose profile and level automatically.
Bitrate settings mirror vp9
tested on macOS 10.15.7 and Ubuntu 20.04 LTS (FFmpeg 4.4)
=> Add support for HEVC video codec

streamer/output_stream.py, streamer/packager_node.py, tests/tests.js
Addresses [ Issue 18](https://github.com/google/shaka-streamer/issues/18)
- Restrict WebM formats to DASH protocol only, preventing WebM formats in HLS
- Restriction is set via Shaka Packager's "dash_only" flag as per discussion in the [ Issue 18 thread](https://github.com/google/shaka-streamer/issues/18)
-  Added and passed unit test
- Tested manually by analyzing command line output and HLS manifest content when "aac" and "opus" audio codecs are specified
-  Ex:
DASH (contains WebM)
HLS (does NOT contain WebM)
=> Restrict WebM formats to DASH protocol

streamer/bitrate_configuration.py, streamer/transcoder_node.py, tests/tests.js
If required output framerate is < input source frame rate adjust configuration accordingly to automatically pull down
=> Adding automatic frame rate pulldown

streamer/transcoder_node.py
Faster vp9 encoding, whilst still maintaining balance between speed/quality.
In my testing, for a given file, this results in ~20% reduction in encoding time.
The subjective difference in output quality appears negligible.
=> Slight speed up of vp9 encoding

streamer/bitrate_configuration.py, streamer/output_stream.py, streamer/transcoder_node.py
This PR removes the `hw:` enum variants, making the enum only for the base codec variants.
If a codec is prefixed with `hw:`, it will be caught in the `_missing_` hook, we will try to know if it can be one of the base variants or not, if it is a base variant we will set the `_hw_acc` to `True` for this codec variant, if not we will fall back the the `super()._missing_` and print the appropriate error message.
=> Using Enum._missing_ hook to generically handle the hw: variants

run_end_to_end_tests.py, shaka-streamer, streamer/controller_node.py, streamer/packager_node.py, streamer/periodconcat_node.py, streamer/util.py, tests/tests.js
Based off of Joey Parrish's [HTTP Upload commit](https://github.com/joeyparrish/shaka-streamer/commit/e3b02679850ee7cf6961d8e5da2f09674f9a07cf) 
- Allow users to specify a HTTP url as an output
- Segments and manifests will be uploaded to the specified url via HTTP PUT
- Urls ending with a '/' will have the slash removed to prevent issues with Google Cloud
- Added unit tests to check for config compatibility errors, such as specifying an HTTP url output with a "multi_period_input" and with "segment_per_file" set to false
- The multi period input list feature is currently structured to use the local file system and does not easily support HTTP uploads. This must be addressed as the multi period input feature continues to evolve, @meryacine. 
- The HTTP upload feature does not make sense if …
=> HTTP url output support

docs/source/overview.rst, docs/source/prerequisites.rst, streamer/input_configuration.py
I think there is nothing to be written about the multiperiod concatenation, using it would be easy given that there is a sample config file for it.
=> docs: Adding `shaka-streamer-binaries` to the prerequisites section

CHANGELOG.md, streamer/autodetect.py, streamer/input_configuration.py
Probing with `'stream=index'` should return the `track_num` if it existed, and an empty string if the input did not exist.
fixes #89
=> fix(errors): probe whether the input exists or not

run_end_to_end_tests.py
Use `werkzeug.utils.secure_filename` to fix arbitrary file reading vulnerabilities.
=> Fix arbitrary file reading vulnerabilities.

.gitignore, package-lock.json, package.json, run_end_to_end_tests.py
It is a best practice for CI to commit package-lock.json and to use
npm ci instead of npm install, for consistent results in CI systems.
Package details were removed from package.json to prevent accidental
publication to npm.  This projects uses node modules for testing, but
is not itself a node module.
=> ci: Commit package-lock.json, use npm ci

streamer/autodetect.py
With some container formats (such as `ts`), ffprobe reports the output twice with newline characters in between. This fix is to take into consideration only the first line of ffprobe's output.
Closes #119
=> fix: only use the first line of ffprobe's output

streamer/autodetect.py
MOV videos captured with iPhone (iOS 16) contain a pipe character right after the frame-rate and the resolution strings, e.g. `32700/1091|` and `1920|1080|`.
Related issue: https://github.com/shaka-project/shaka-streamer/issues/127
Example ffprobe:
```
/Users/hmishinev/Downloads/IMG_4348.mov \
-select_streams v:0 -show_entries stream=avg_frame_rate -of compact=p=0:nk=1
ffprobe version 5.1 Copyright (c) 2007-2022 the FFmpeg developers
built with Apple clang version 13.1.6 (clang-1316.0.21.2.5)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus …
```
=> fix: Fix frame-rate and resolution auto-detection edge case

streamer/bitrate_configuration.py
=> feat: Add OPUS mp4 support

run_end_to_end_tests.py, tests/karma.conf.js, tests/tests.js
The --no-cleanup flag allows you to inspect the output files after a test run, for debugging purposes.
The --filter flag lets you run a subset of tests based on a text or regex match (matches if either technique matches, so you don't have to regex-escape an exact test name).
=> test: Add --no-cleanup and --filter flags to test runner

run_end_to_end_tests.py
Multiperiod tests make requests for content in subfolders of the output folder.  However, the werkzeug utility "secure_filename" ruins this by replacing "/" with "_".
secure_filename() was used to prevent breakout attempts (requests for "../../../../../../../boot/vmlinuz" for example), but was intended by its authors for use in file uploads where a single filename was given, not a full path.  So we replace this with a simple check for ".." in the path.
This went unnoticed since the introduction of multi-period support because there was no GitHub Actions workflow to run the tests.
=> test: Fix multiperiod tests

tests/tests.js
We no longer output opus in WebM, but rather in MP4.  Therefore the WebM filter test did not work any more when checking for opus. Instead, it must check for vp9, which we still put into WebM.
This went unnoticed because there was no GitHub Actions workflow to run the tests.
=> test: Fix WebM filter test

binaries/build_wheels.py, binaries/setup.py, binaries/streamer_binaries/__init__.py, streamer/__init__.py, streamer/controller_node.py, streamer/min_versions.py, streamer/transcoder_node.py
- Update to the latest Shaka Packager (v3.2.0) and FFmpeg (n7.1) releases
- Add support for macOS arm64
- Add support for hardware encoding on Ubuntu Linux 22.04 and 24.04
- Adjust AV1 encoding options to match new FFmpeg release
=> feat: Expand binary platforms and hardware encoding

streamer/proxy_node.py
To avoid rate limit failures (HTTP 429 "Too many requests"), avoid writing to the same file multiple times per second.  This happens only on MPD and M3U8 files.
=> fix(cloud): Avoid rate limit issues on live streams

streamer/proxy_node.py
This allows Packager to remove old segments from cloud storage automatically.
See https://github.com/shaka-project/shaka-packager/pull/1442
=> feat(cloud): Add cloud delete support

streamer/proxy_node.py
This mistake slipped through because we are not yet validating every PR with mypy.
=> fix: Fix typing of log_request

streamer/proxy_node.py
Uses basic retry settings for GCS and S3.
If we do not pass these params, GCS would normally only retry if certain params were passed so that it knew the operation was definitely idempotent.  We know our use case, so we know we can safely retry.
There will never be two versions of the same segment file, or two concurrent writes to the MPD, for example.  So both uploads and deletes can be safely retried.
=> fix(cloud): Retry on all failures

.github/workflows/publish-docs.yaml
If two commits hit main in rapid succession, we get two concurrent runs of the docs workflow.  Let the new one replace the old one.
=> ci: Fix concurrent runs of docs workflow

docs/source/overview.rst, setup.py, streamer/configuration.py
Also reverts old fixes specific to Python 3.6.
Python 3.9 is the last living release, supported until EOY25.
=> feat!: Bump minimum Python version to 3.9

streamer/proxy_node.py
On some versions, mypy thinks the file handle from the web server is BinaryIO, in others, BufferedIOBase.  We don't care which it is, as both have the methods we care about.
I tried the IOBase class from "io", but I get failures on certain devices.  This is the best solution I've found so far.
=> test: Fix mypy types

streamer/packager_node.py
Set to true to signal DolbyVision using the modern supplemental codecs approach instead of the legacy duplicate representations approach
=> feat(Packager): Use always --use_dovi_supplemental_codecs option

streamer/packager_node.py
Since we don't support key rotation, adding this argument is safe, and it also helps ShakaPlayer reduce startup latency, as well as helping a lot in the case where HLS identity is used.
=> feat: Always use HLS session keys to improve player startup performance

streamer/packager_node.py
Instead of something like this (Packager's default):
```
#EXT-X-MEDIA:TYPE=AUDIO,URI="aac.m3u8",GROUP-ID="audio",LANGUAGE="en",NAME="aac",DEFAULT=NO,AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="ac3.m3u8",GROUP-ID="audio",LANGUAGE="en",NAME="ac3",DEFAULT=NO,AUTOSELECT=YES,CHANNELS="2"
#EXT-X-STREAM-INF:BANDWIDTH=973060,AVERAGE-BANDWIDTH=973259,CODECS="avc1.4d401e,mp4a.40.2,ac3",RESOLUTION=846x360,FRAME-RATE=24.000,AUDIO="audio",CLOSED-CAPTIONS=NONE
video.m3u8
```
We should split the audio groups by codec:
```
#EXT-X-MEDIA:TYPE=AUDIO,URI="aac.m3u8",GROUP-ID="aac",LANGUAGE="en",NAME="aac",DEFAULT=NO,AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="ac3.m3u8",GROUP-ID="ac3",LANGUAGE="en",NAME="ac3",DEFAULT=NO,AUTOSELECT=YES,CHANNELS="2" …
```
=> fix(HLS): Fix audio grouping by codec

.github/workflows/build-and-test.yaml, .github/workflows/publish-docs.yaml, .github/workflows/release-please.yaml
This was found by auditing workflows based on research published here:
https://github.com/joeyparrish/workflow-cheat-sheet
The research was prompted by this repo's PR workflow testing the wrong ref.
=> ci: Fix workflow events

.github/workflows/build-and-test.yaml
My previous fix to this workflow made a mistake in the syntax of the checkout ref.
=> ci: Fix bad workflow syntax

binaries/build_wheels.py, binaries/streamer_binaries/__init__.py
According to https://pypi.org/help/#file-size-limit, there is a limit of 100MB for any given wheel.  Our Linux x64 wheel is 101MB, and so the 1.0.0 release failed to upload.
This reduces the binary size by avoiding distro-specific versions of ffprobe.  The only thing we get from distro-specific versions of ffmpeg is hardware-encoding support, but that doesn't apply to ffprobe.  So it was wasteful to include distro-specific ffprobe builds.
This reduces the Linux x64 wheel size from 101MB to 69MB.
=> fix(binaries): Bring PyPi package size under the limit

.github/workflows/build-and-test.yaml, build-matrix.json, run_end_to_end_tests.py, tests/karma.conf.js, tests/tests.js
=> ci: Enable testing on Linux arm64

.github/workflows/build-and-test.yaml
Closes #197
Could have prevented #194
For a test run with macOS arm64 enabled, showing how this would have caught #194, see https://github.com/joeyparrish/shaka-streamer/actions/runs/11762714145/job/32765885894
Once https://github.com/shaka-project/static-ffmpeg-binaries/issues/51 is closed, and we have new builds in the binary package, we can re-enable macOS arm64 testing for #179.
=> ci: Test binary installation

binaries/build_wheels.py
I used docs on the [Python wheel format][] to determine that the bit with the OS and CPU is called the "platform tag".  Then I found a [discussion of macOS platform tags][] that gave me the hint that arm64 wheels need to specify macOS 11 at a minimum.
[Python wheel format]: https://peps.python.org/pep-0427/
[discussion of macOS platform tags]: https://github.com/pypa/wheel/issues/387
Closes #194
=> fix(binaries): Fix arm64 mac binary tags

binaries/build_wheels.py
See https://github.com/shaka-project/static-ffmpeg-binaries/issues/51 and https://github.com/shaka-project/static-ffmpeg-binaries/pull/54
=> fix(binaries): Fix macOS arm64 ffmpeg crash

streamer/packager_node.py
I was confused about the placement of --use_dovi_supplemental_codecs, so this moves it to a place where I would expect to find common options that are always enabled.
=> chore: Move Packager options

tests/tests.js
`WARN LOG: 'Player w/ mediaElement has been deprecated and will be removed in v5.0 . We are currently at version v4.11 . Additional information: Please migrate from initializing Player with a mediaElement; use the attach method instead.'`
=> test: Fix Shaka Player warning

streamer/bitrate_configuration.py, tests/tests.js
VP9 in MP4 has been supported in Chrome since Chrome 60 (https://chromestatus.com/feature/5762080762232832), which was released in June 2017, so it's been over 7 years!
=> feat: Use by default VP9 with mp4

binaries/build_wheels.py, streamer/min_versions.py, streamer/packager_node.py
Instruct Packager to ignore HTTP output failures, so that the pipeline overall doesn't fail during a live stream.  Once the system recovers, segments will be missing, but the stream overall will survive.
This requires a new release of Shaka Packager (v3.4.0).
Closes #195
=> feat: Recover from upload failures

README.md, binaries/README.md, binaries/setup.py
The binary package on pypi has almost no information.  This adds a more detailed README to make the pypi landing page more explanatory.
This also improves the main README to mention the binary package.  It is strongly recommended, and should be mentioned in the brief instructions on the main package README.
Classified as a "fix" only so that the release workflow will trigger, so that we can update the docs on pypi with a new release.
=> fix(docs): Improve READMEs and pypi docs for binaries

.github/workflows/build-and-test.yaml, .github/workflows/publish-docs.yaml
See actions/checkout#485 and https://johnstawinski.com/2024/01/11/playing-with-fire-how-we-executed-a-critical-supply-chain-attack-on-pytorch/
In short, it is a terrible idea to persist even our default credentials after checkout. There's no call for that, so we will now set `persist-credentials: false` on all checkout actions.
=> ci: Do not persist credentials after checkout

.github/workflows/release-please.yaml
Replaces a third-party action with the official GitHub command line, to avoid exposing priveleged tokens to a third-party
=> ci: Update release workflow

streamer/bitrate_configuration.py, streamer/periodconcat_node.py
A newer linter complains about our codec enums:
> streamer/bitrate_configuration.py:40: error: Enum members must be left unannotated  [misc]
> streamer/bitrate_configuration.py:40: note: See https://typing.readthedocs.io/en/latest/spec/enums.html#defining-members
And also this shows up in Python 3.12:
> streamer/periodconcat_node.py:128: SyntaxWarning: invalid escape sequence '\{'
>  namespace_matches = re.search('\{([^}]*)\}', concat_mpd.tag)
=> chore: Fix mypy linter errors and warnings

config_files/bitrate_hls_config.yaml
The key recognized by shaka-streamer is "hevc", not "h265".
=> docs: Fix HEVC sample config

requirements.txt, setup.py
This dependency was introduced in 1.2.0 to enable `typing` module features not yet standard in Python 3.9, so that everything could be properly typed without requiring newer Python versions yet.
=> fix: Add missing dependency on typing_extensions

.github/workflows/build-and-test.yaml, build-matrix.json
These are no longer required since GitHub launched their own Linux/arm64 runners.
See https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
=> ci: Stop using self-hosted Linux/arm64 runners

.github/workflows/build-and-test.yaml, .github/workflows/settings.yaml
With this change, GitHub will start to enforce "require approval" settings for the repo, which `pull_request_target` allows PR authors to get around.
To stop using `pull_request_target`, we also have to stop using `vars`, which are not available on `pull_request` triggers.  Instead, we use the "environments" trick used by Shaka Packager's workflows before `vars` was introduced to GitHub Actions.  This is a safer system.
=> ci: Switch pull_request_target to pull_request

streamer/cloud/__init__.py
The cloud/ folder was added in 1.2.0, but was not being packaged correctly due to a missing `__init__.py` file.  This bug affected the 1.2.0 and 1.2.1 releases, making both unusable.
Fixes #234
=> fix: Fix missing cloud/ subfolder

streamer/packager_node.py, streamer/pipeline_configuration.py
This allows passing the `--hls_key_uri <uri>` command-line option.
=> feat: Add configuration option for "hls_key_uri"
